Description: >
  This template deploys a ec2 instance

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:  vpc-0ff14ae6d009a91bc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  UdacityInstance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-052efd3df9dad4825"
      SecurityGroupIds: 
        - !GetAtt InstanceSecurityGroup.GroupId
      KeyName: "cicd"
      InstanceType: t2.micro
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdk"
        Ebs: 
          VolumeSize: "10"
      Tags:
        - Key: Name
          Value: Udacity
      