version: 2.1


jobs:
  configure_infrastructure:
    docker:
      - image:  python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [0f:4c:b2:88:fd:fb:b1:61:fe:fc:c0:b3:a0:06:b0:32]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml

workflows:
  configure-infrastructure-workflow:
    jobs:
      - configure_infrastructure

